# Generated by Django 4.2.2 on 2025-03-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=2)),
                ('lichess_username', models.CharField(max_length=150, unique=True)),
                ('lichess_rating_bullet', models.IntegerField(default=0)),
                ('lichess_rating_blitz', models.IntegerField(default=0)),
                ('lichess_rating_rapid', models.IntegerField(default=0)),
                ('lichess_rating_classical', models.IntegerField(default=0)),
                ('fide_id', models.IntegerField(default=None, unique=True)),
                ('fide_rating_blitz', models.IntegerField(default=0)),
                ('fide_rating_rapid', models.IntegerField(default=0)),
                ('fide_rating_classical', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
