# Generated by Django 4.2.2 on 2025-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fide_id',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
