# Generated by Django 4.2.2 on 2025-03-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0002_alter_player_fide_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('refereeNumber', models.CharField(default=-1, max_length=32)),
            ],
        ),
    ]
