# Generated by Django 4.2.2 on 2025-03-11 20:03

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chess_models', '0003_referee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaApuntadoATorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_models.player')),
            ],
        ),
        migrations.CreateModel(
            name='RankingSystemClass',
            fields=[
                ('value', models.CharField(choices=[('BU', 'Buchholz'), ('BC', 'Buchholz Cut 1'), ('BA', 'Buchholz Average'), ('SB', 'Sonneborn-Berger'), ('PS', 'Plain Score'), ('WI', 'No. Wins'), ('BT', 'No. games played with Black')], max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('start_date', models.DateTimeField(verbose_name='??????????????????')),
                ('end_date', models.DateTimeField()),
                ('max_update_time', models.IntegerField(default=43200)),
                ('only_administrative', models.BooleanField(default=False)),
                ('tournament_type', models.CharField(max_length=2)),
                ('tournament_speed', models.CharField(max_length=2)),
                ('board_type', models.CharField(max_length=3)),
                ('win_points', models.FloatField(default=1.0)),
                ('draw_points', models.FloatField(default=0.5)),
                ('lose_points', models.FloatField(default=0.0)),
                ('timeControl', models.CharField(default='15+0', max_length=32)),
                ('number_of_rounds_for_swiss', models.IntegerField(default=0)),
                ('administrativeUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_models.user')),
                ('players', models.ManyToManyField(through='chess_models.FechaApuntadoATorneo', to='chess_models.player')),
                ('rankingList', models.ManyToManyField(to='chess_models.rankingsystemclass')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_models.referee')),
            ],
        ),
        migrations.AddField(
            model_name='fechaapuntadoatorneo',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_models.tournament'),
        ),
    ]
