# Generated by Django 4.2.2 on 2025-03-12 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chess_models', '0004_fechaapuntadoatorneo_rankingsystemclass_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='administrativeUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
