# Generated by Django 4.2.2 on 2025-03-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0005_alter_tournament_administrativeuser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
