# Generated by Django 4.2.2 on 2025-03-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0006_alter_tournament_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('finish', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_models.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('result', models.CharField(default='*', max_length=1)),
                ('rankingOrder', models.IntegerField(default=0)),
                ('black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='chess_models.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_models.round')),
                ('white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='chess_models.player')),
            ],
        ),
    ]
