# Generated by Django 4.2.2 on 2025-03-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0007_round_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
