# Generated by Django 4.2.2 on 2025-03-12 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chess_models', '0008_alter_tournament_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='administrativeUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
