# Generated by Django 4.2.2 on 2025-03-12 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0009_alter_tournament_administrativeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chess_models.referee'),
        ),
    ]
