# Generated by Django 4.2.2 on 2025-03-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0010_alter_tournament_referee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
