# Generated by Django 4.2.2 on 2025-03-12 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0011_alter_round_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='chess_models.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='chess_models.player'),
        ),
    ]
