# Generated by Django 4.2.2 on 2025-03-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0012_alter_game_black_alter_game_white'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lichess_username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
