# Generated by Django 4.2.2 on 2025-03-18 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chess_models', '0013_alter_player_lichess_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='administrativeUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, through='chess_models.FechaApuntadoATorneo', to='chess_models.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rankingList',
            field=models.ManyToManyField(blank=True, null=True, to='chess_models.rankingsystemclass'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chess_models.referee'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
