# Generated by Django 4.2.2 on 2025-03-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0014_alter_tournament_administrativeuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, through='chess_models.FechaApuntadoATorneo', to='chess_models.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rankingList',
            field=models.ManyToManyField(blank=True, to='chess_models.rankingsystemclass'),
        ),
    ]
