# Generated by Django 4.2.2 on 2025-04-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0015_alter_tournament_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
