# Generated by Django 4.2.2 on 2025-04-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_models', '0016_alter_player_country_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='referee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chess_models.referee'),
        ),
    ]
